# Generated by Django 5.1.3 on 2025-01-31 04:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(null=True, verbose_name='ลำดับ')),
                ('completion_status', models.BooleanField(default=False, null=True, verbose_name='สถานะจบงาน')),
                ('year', models.CharField(max_length=4, null=True, verbose_name='ปี พ.ศ.')),
                ('date', models.DateField(null=True, verbose_name='วันที่')),
                ('month', models.IntegerField(blank=True, null=True, verbose_name='เดือน')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='เวลา')),
                ('job_number', models.CharField(max_length=50, null=True, verbose_name='เลขงาน')),
                ('bill_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='เลขที่บิล')),
                ('technician_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อช่าง')),
                ('technician_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์ติดต่อช่าง')),
                ('project_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัสโครงการ')),
                ('project_name', models.CharField(max_length=100, null=True, verbose_name='โครงการ')),
                ('house_number', models.CharField(max_length=50, null=True, verbose_name='บ้านเลขที่')),
                ('plot_number', models.CharField(max_length=50, null=True, verbose_name='แปลง')),
                ('house_type', models.CharField(max_length=50, null=True, verbose_name='แบบบ้าน')),
                ('transfer_date', models.DateField(blank=True, null=True, verbose_name='วันที่โอน')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='วันที่หมดประกัน')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='อาการที่แจ้ง')),
                ('status', models.CharField(max_length=50, null=True, verbose_name='สถานะ')),
                ('appointment_date', models.DateField(blank=True, null=True, verbose_name='วันนัด')),
                ('appointment_time', models.TimeField(blank=True, null=True, verbose_name='เวลานัด')),
                ('equipment_status', models.TextField(blank=True, default='', null=True, verbose_name='วัสดุ/อุปกรณ์ที่ผิดปกติ')),
                ('cause_found', models.TextField(blank=True, default='', null=True, verbose_name='สาเหตุที่ตรวจพบ')),
                ('solution', models.TextField(blank=True, default='', null=True, verbose_name='การแก้ไข')),
                ('technician_names', models.CharField(blank=True, max_length=200, null=True, verbose_name='รายชื่อช่าง')),
                ('notes', models.TextField(blank=True, default='', null=True, verbose_name='หมายเหตุ')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='จำนวนเงิน')),
                ('service_images', models.TextField(blank=True, default='', null=True, verbose_name='ลิงก์รูปภาพ')),
                ('additional_notes', models.TextField(blank=True, default='', null=True, verbose_name='หมายเหตุเพิ่มเติม')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อลูกค้า')),
                ('customer_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='เบอร์ติดต่อ')),
                ('imported', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_records', to='accounts.customer')),
            ],
            options={
                'verbose_name': 'บันทึกการบริการ',
                'verbose_name_plural': 'บันทึกการบริการ',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRecordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_fields', models.JSONField(help_text='บันทึกฟิลด์ที่มีการเปลี่ยนแปลง')),
                ('action', models.CharField(choices=[('create', 'สร้าง'), ('update', 'แก้ไข'), ('delete', 'ลบ')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='รายละเอียดการเปลี่ยนแปลง')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='service.servicerecord')),
            ],
            options={
                'verbose_name': 'ประวัติการแก้ไข',
                'verbose_name_plural': 'ประวัติการแก้ไข',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('repair', 'แจ้งซ่อม'), ('install', 'ซื้ออะไหล่'), ('all_in', 'ต้องการแจ้งซ่อมและซื้ออะไหล่')], max_length=20)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('appointment_time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(help_text='อ้างอิงจากรายละเอียดปัญหาที่ลูกค้าแจ้งตอนลงทะเบียน', verbose_name='รายละเอียดปัญหา')),
                ('status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('assigned', 'มอบหมายงานแล้ว'), ('pending_advice', 'รอคำปรึกษาจากช่าง'), ('advice_given', 'ให้คำปรึกษาแล้ว'), ('confirmed', 'ยืนยันการแจ้งซ่อม'), ('accepted', 'รับงาน'), ('traveling', 'กำลังเดินทาง'), ('arrived', 'ถึงจุดหมาย'), ('fixing', 'กำลังแก้ไข'), ('completed', 'จบงาน'), ('cancelled', 'ยกเลิก'), ('rescheduled', 'เลื่อนนัด')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='ยืนยันโดยฝ่ายบริการ')),
                ('warranty_status', models.CharField(choices=[('in_warranty', 'อยู่ในประกัน'), ('out_of_warranty', 'ไม่อยู่ในประกัน'), ('pending_warranty', 'รอการตัดสินใจ')], default='pending_warranty', max_length=20, verbose_name='สถานะประกัน')),
                ('need_advice', models.BooleanField(default=False, help_text='เลือกตัวเลือกนี้หากต้องการให้ช่างแนะนำก่อนดำเนินการ', verbose_name='ต้องการคำแนะนำจากช่าง')),
                ('customer_confirmed', models.BooleanField(default=False, verbose_name='ลูกค้ายืนยันการดำเนินการ')),
                ('technician_advice', models.TextField(blank=True, null=True, verbose_name='คำแนะนำจากช่าง')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ประมาณการค่าใช้จ่าย')),
                ('cost_note', models.TextField(blank=True, verbose_name='หมายเหตุค่าใช้จ่าย')),
                ('cost_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='วันที่กำหนดค่าใช้จ่าย')),
                ('service_type', models.CharField(blank=True, choices=[('normal', 'ระบบไฟปกติ'), ('full_checkup', 'ระบบ Full Check Up'), ('air_flow', 'ระบบ Air flow/Air Plus'), ('checkup_air_plus', 'ระบบ Check up Program Air plus')], max_length=50, null=True, verbose_name='ประเภทการซ่อม')),
                ('warranty_start_date', models.DateField(blank=True, null=True, verbose_name='วันที่เริ่มประกัน')),
                ('warranty_end_date', models.DateField(blank=True, null=True, verbose_name='วันที่สิ้นสุดประกัน')),
                ('service_category', models.CharField(blank=True, choices=[('ELECTRICAL', 'ตู้ไฟ'), ('AIRPLUS', 'Air Plus'), ('OTHER', 'บริการอื่นๆ')], max_length=20, null=True, verbose_name='ประเภทบริการ')),
                ('service_level', models.CharField(blank=True, choices=[('NORMAL', 'บริการแบบปกติ'), ('FULL', 'บริการแบบ Full Check up')], max_length=10, null=True, verbose_name='ระดับบริการ')),
                ('ac_count', models.IntegerField(blank=True, choices=[(1, '1 เครื่อง'), (2, '2 เครื่อง')], null=True, verbose_name='จำนวนเครื่องปรับอากาศ')),
                ('calculated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ราคาประเมิน')),
                ('cost_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_updates', to=settings.AUTH_USER_MODEL, verbose_name='ผู้กำหนดค่าใช้จ่าย')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='accounts.customer')),
                ('service_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='service.servicerecord', verbose_name='บันทึกการบริการ')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'การแจ้งซ่อม',
                'verbose_name_plural': 'การแจ้งซ่อม',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_proposals', to='service.servicerequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianJobStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'ยืนยันการแจ้งซ่อม'), ('accepted', 'รับงาน'), ('traveling', 'กำลังเดินทาง'), ('arrived', 'ถึงจุดหมาย'), ('fixing', 'กำลังแก้ไข'), ('completed', 'จบงาน'), ('cancelled', 'ยกเลิก'), ('rescheduled', 'เลื่อนนัด')], max_length=20, verbose_name='สถานะ')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาอัพเดท')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='service.servicerequest')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'สถานะงานช่าง',
                'verbose_name_plural': 'สถานะงานช่าง',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_proposals', to='service.servicerequest')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียดการตอบกลับ')),
                ('service_type', models.CharField(blank=True, choices=[('normal', 'ระบบไฟปกติ'), ('full_checkup', 'ระบบ Full Check Up'), ('air_flow', 'ระบบ Air flow/Air Plus'), ('checkup_air_plus', 'ระบบ Check up Program Air plus')], max_length=50, null=True, verbose_name='ประเภทการซ่อม')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ประมาณการค่าใช้จ่าย')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่ตอบกลับ')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_responses', to='service.servicerequest')),
            ],
            options={
                'verbose_name': 'การตอบกลับของช่าง',
                'verbose_name_plural': 'การตอบกลับของช่าง',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_images/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('image_hash', models.CharField(blank=True, max_length=64)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_images', to='service.servicerequest')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'unique_together': {('service_request', 'image_hash')},
            },
        ),
    ]
