# Generated by Django 5.1.3 on 2025-02-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_servicerequest_ac_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicianjobstatus',
            name='status',
            field=models.CharField(choices=[('assigned', 'ได้รับมอบหมายงาน'), ('confirmed', 'ยืนยันการแจ้งซ่อม'), ('accepted', 'รับงาน'), ('traveling', 'กำลังเดินทาง'), ('arrived', 'ถึงจุดหมาย'), ('fixing', 'กำลังแก้ไข'), ('completed', 'จบงาน'), ('cancelled', 'ยกเลิก'), ('rescheduled', 'เลื่อนนัด')], max_length=20, verbose_name='สถานะ'),
        ),
    ]
