# Generated by Django 5.1.3 on 2025-02-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_technicianjobstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='project_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัสโครงการ'),
        ),
    ]
